builds:
  - env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    main: ./cmd/actions-runner-processor/

archives:
  - format: tar.gz
    name_template: "actions-runner-processor_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
